version: '3.8'
services:
  kindred_storage:
    image: postgres:12-alpine
    restart: unless-stopped
    networks:
      - webnet
    environment:
      POSTGRES_USER: ${DATABASE_USER:-postgres}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-postgres}
      POSTGRES_DB: ${DATABASE_NAME:-kindred}
    ports:
      - '5433:5432'
    volumes:
      - kindred_storage:/var/lib/postgresql/data

  app_server:
    depends_on:
      - kindred_storage
    build: .
    restart: unless-stopped
    networks:
      - webnet
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "60061:60061"
    environment:
      NODE_ENV: production
      DATABASE_NAME: ${DATABASE_NAME:-kindred}
      DATABASE_HOST: kindred_storage
      DATABASE_USER: ${DATABASE_USER:-postgres}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD:-postgres}
    command: ["npm", "run", "start:prod"]

volumes:
  kindred_storage:

networks:
  webnet: