# fly.toml app configuration file generated for kindred-backend on 2024-03-22T01:52:10+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'kindred-backend'
primary_region = 'ams'

[build]

[http_service]
  internal_port = 60061
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[deploy]
  release_command = "npm run migration"

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
